4, 13). I föregående kapitel gjordes en EDA på datasetet “hr_employee_data.xlsx”.
Gör nu ett komplett ML-flöde där den beroende variabeln, 𝑦, är left.
Om den variabeln är 1 så betyder det att den anställde har lämnat företaget och
om den är 0 så betyder det att den anställde inte har lämnat företaget, det vill säga jobbar kvar.

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import root_mean_squared_error

In [9]:
df = pd.read_excel("hr_employee_data.xlsx")
df.head()

,Emp_Id,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,IND02438,0.38,0.53,2,157,3,0,1,0,sales,low
1,IND28133,0.80,0.86,5,262,6,0,1,0,sales,medium
2,IND07164,0.11,0.88,7,272,4,0,1,0,sales,medium
3,IND30478,0.72,0.87,5,223,5,0,1,0,sales,low
4,IND24003,0.37,0.52,2,159,3,0,1,0,sales,low

In [ ]:
# Det finns 3 kolumner med datatypen objekt och inga NULL-värden.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Emp_Id                 14999 non-null  object
 1   satisfaction_level     14999 non-null  float64
 2   last_evaluation        14999 non-null  float64
 3   number_project         14999 non-null  int64
 4   average_montly_hours   14999 non-null  int64
 5   time_spend_company     14999 non-null  int64
 6   Work_accident          14999 non-null  int64
 7   left                   14999 non-null  int64
 8   promotion_last_5years  14999 non-null  int64
 9   Department             14999 non-null  object
 10  salary                 14999 non-null  object
dtypes: float64(2), int64(6), object(3)
memory usage: 1.3+ MB

In [11]:
# Här tar jag bort Emp_ID för att den inte är relevant för prediktionen.

X = df.drop(columns=["left", "Emp_Id"])
y = df["left"]

# Nu gör jag om kategoriska variabler till numeriska variabler så att de kan användas i modellen.
X = pd.get_dummies(X, drop_first=True)
X.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years,Department_RandD,Department_accounting,Department_hr,Department_management,Department_marketing,Department_product_mng,Department_sales,Department_support,Department_technical,salary_low,salary_medium
0,0.38,0.53,2,157,3,0,0,False,False,False,False,False,False,True,False,False,True,False
1,0.80,0.86,5,262,6,0,0,False,False,False,False,False,False,True,False,False,False,True
2,0.11,0.88,7,272,4,0,0,False,False,False,False,False,False,True,False,False,False,True
3,0.72,0.87,5,223,5,0,0,False,False,False,False,False,False,True,False,False,True,False
4,0.37,0.52,2,159,3,0,0,False,False,False,False,False,False,True,False,False,True,False

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Jag testar både en linjär regression och en beslutsträd regression för att se vilken som presterar bäst på datan.
lr = LinearRegression()
dtr = DecisionTreeRegressor(random_state=42)

lr.fit(X_train, y_train)
dtr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)
dtr_pred = dtr.predict(X_test)

# Här kan vi se att i detta exempel presterar beslutsträd regressionen bättre än den linjära regressionen.
lr_rmse = root_mean_squared_error(y_test, lr_pred)
dtr_rmse = root_mean_squared_error(y_test, dtr_pred)
print(f"RMSE for Linear Regression: {lr_rmse:.2f}")
print(f"RMSE for Decision Tree Regression: {dtr_rmse:.2f}")

RMSE for Linear Regression: 0.38
RMSE for Decision Tree Regression: 0.15